name: FriendSystem
version: '1.0'
author: Niko
main: net.fununity.friendsystem.FriendSystemSpigot
api-version: '1.19'
depend:
  - FunUnityAPI
  - CloudSystem-Client
  - DatabaseHandler
  - TranslationHandler